"""Two verifications that leakage is absent, not merely guarded against.

The numbered controls in ``test_leakage.py`` each assert one rule the
code was written to follow. These two do something different: they look
for the *effect* of a leak without being told where it would come from.

    future-perturbation   change a booking that happens after a row's
                          origin; every feature of that row must be
                          byte-identical. Catches an as-of violation
                          structurally, without naming the column.

    shuffled-label        break the link between features and target,
                          then train. A head that still beats its own
                          majority-class prior by more than sampling
                          noise is reading the answer through a channel
                          nobody declared.

Neither substitutes for the other. A perturbation test cannot see a leak
that travels through the label distribution; a negative control cannot
localise one it does find.

The perturbation cases are generated by Hypothesis over timezone-aware
instants, so the search is not limited to the offsets a human thought
to write down.
"""

from __future__ import annotations

import datetime
import pathlib
import zoneinfo

import hypothesis
from hypothesis import strategies as st
import numpy as np
import pandas as pd
import pytest

from facility_prediction import config as config_module
from facility_prediction.data import generate, samples, split
from facility_prediction.features import features
from facility_prediction.models import train

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
SMOKE_PATH = REPO_ROOT / "configs" / "smoke.yaml"

KOLKATA = zoneinfo.ZoneInfo("Asia/Kolkata")

# Hypothesis's own deadline measures one example at a time, and a
# feature build is far slower than the default allows. The budget that
# matters here is the whole test's, not one example's.
_SETTINGS = hypothesis.settings(
    max_examples=25,
    deadline=None,
    suppress_health_check=[hypothesis.HealthCheck.function_scoped_fixture],
)

# A shuffled head may still land above its majority prior by chance.
# The floor is the plan's, and it is declared here rather than inferred
# from whatever the run produced.
_NOISE_FLOOR = 0.02
_NOISE_SIGMAS = 2.0


@pytest.fixture(scope="module")
def smoke_config() -> config_module.Config:
    return config_module.load_config(SMOKE_PATH)


@pytest.fixture(scope="module")
def smoke_bookings(smoke_config) -> pd.DataFrame:
    return generate.generate_bookings(smoke_config)


@pytest.fixture(scope="module")
def smoke_samples(smoke_bookings, smoke_config) -> pd.DataFrame:
    return samples.build_samples(smoke_bookings, smoke_config)


@pytest.fixture(scope="module")
def smoke_features(smoke_samples, smoke_bookings, smoke_config):
    return features.build_features(smoke_samples, smoke_bookings, smoke_config)


def _rows_of(smoke_samples, smoke_features, smoke_config, wanted: str):
    """Return the feature rows belonging to one split.

    Args:
        smoke_samples: The sample table.
        smoke_features: The feature table.
        smoke_config: Validated configuration.
        wanted: The split label to keep.

    Returns:
        Those feature rows, in their original order.
    """
    cutoffs = split.compute_cutoffs(smoke_samples, smoke_config)
    labelled = split.assign_split(smoke_samples, cutoffs)
    keep = set(
        labelled.loc[
            labelled[split.SPLIT_COLUMN] == wanted, split.SAMPLE_ID_COLUMN
        ]
    )
    return smoke_features.loc[smoke_features["sample_id"].isin(keep)]


@pytest.fixture(scope="module")
def training_rows(smoke_samples, smoke_features, smoke_config):
    return _rows_of(smoke_samples, smoke_features, smoke_config, split.TRAIN)


@pytest.fixture(scope="module")
def validation_rows(smoke_samples, smoke_features, smoke_config):
    return _rows_of(
        smoke_samples, smoke_features, smoke_config, split.VALIDATION
    )


# --- the future-perturbation property ---------------------------------


def _rows_before(
    table: pd.DataFrame, samples_frame: pd.DataFrame, instant: pd.Timestamp
) -> pd.Index:
    """Return the positions of feature rows whose origin precedes an instant.

    Args:
        table: The feature table.
        samples_frame: The sample table carrying each row's origin.
        instant: The instant a perturbation was applied at.

    Returns:
        The index of every feature row that could not legally have seen
        an event at or after ``instant``.
    """
    origins = samples_frame.set_index("sample_id")["origin"]
    aligned = table["sample_id"].map(origins)
    return table.index[aligned < instant]


def _perturb_after(
    bookings: pd.DataFrame, instant: pd.Timestamp, facility: str
) -> pd.DataFrame:
    """Return the bookings with every event at or after an instant moved.

    The perturbation is deliberately crude — it changes the facility of
    every later booking. A feature that reads the future for any reason
    will move; one that respects its as-of bound cannot.

    Args:
        bookings: The booking table.
        instant: Perturb events at or after this instant.
        facility: The facility name to overwrite them with.

    Returns:
        A perturbed copy; the original is untouched.
    """
    perturbed = bookings.copy()
    later = perturbed["booking_timestamp"] >= instant
    perturbed.loc[later, "facility_id"] = facility
    return perturbed


@hypothesis.given(
    offset_hours=st.integers(min_value=1, max_value=24 * 120),
    facility_index=st.integers(min_value=0, max_value=7),
)
@_SETTINGS
def test_a_future_booking_cannot_change_an_earlier_feature_row(
    smoke_bookings,
    smoke_samples,
    smoke_features,
    smoke_config,
    offset_hours,
    facility_index,
):
    start = smoke_bookings["booking_timestamp"].min()
    instant = start + datetime.timedelta(hours=offset_hours)
    facility = smoke_config.facility_names[
        facility_index % len(smoke_config.facility_names)
    ]
    perturbed = _perturb_after(smoke_bookings, instant, facility)
    hypothesis.assume(not perturbed.equals(smoke_bookings))

    rebuilt = features.build_features(smoke_samples, perturbed, smoke_config)

    earlier = _rows_before(smoke_features, smoke_samples, instant)
    hypothesis.assume(len(earlier) > 0)
    pd.testing.assert_frame_equal(
        rebuilt.loc[earlier], smoke_features.loc[earlier]
    )


@hypothesis.given(offset_hours=st.integers(min_value=1, max_value=24 * 120))
@_SETTINGS
def test_deleting_future_bookings_cannot_change_an_earlier_feature_row(
    smoke_bookings, smoke_samples, smoke_features, smoke_config, offset_hours
):
    # Perturbing values is one failure mode; removing events entirely is
    # another, and a feature that counted rows rather than reading them
    # would only fail this one.
    start = smoke_bookings["booking_timestamp"].min()
    instant = start + datetime.timedelta(hours=offset_hours)
    kept = smoke_bookings.loc[smoke_bookings["booking_timestamp"] < instant]
    hypothesis.assume(len(kept) < len(smoke_bookings))
    hypothesis.assume(not kept.empty)

    surviving = smoke_samples.loc[
        smoke_samples["origin"] < instant, "sample_id"
    ]
    hypothesis.assume(len(surviving) > 0)
    trimmed = features.build_features(
        smoke_samples.loc[smoke_samples["sample_id"].isin(set(surviving))],
        kept,
        smoke_config,
    )
    earlier = smoke_features.loc[
        smoke_features["sample_id"].isin(set(surviving))
    ]
    pd.testing.assert_frame_equal(
        trimmed.reset_index(drop=True), earlier.reset_index(drop=True)
    )


def test_the_same_perturbation_does_move_a_row_it_is_allowed_to_move(
    smoke_bookings, smoke_samples, smoke_features, smoke_config
):
    # The property above is only evidence if the comparison it makes can
    # detect anything at all. Apply the identical perturbation to events
    # BEFORE a row's origin — which the features are supposed to read —
    # and that row must change. If it does not, the comparison is blind
    # and the passing property tests say nothing.
    latest = smoke_samples.loc[[smoke_samples["origin"].idxmax()]]
    instant = latest["origin"].iloc[0]
    unseen = smoke_config.facility_names[-1]
    perturbed = smoke_bookings.copy()
    earlier = perturbed["booking_timestamp"] < instant
    perturbed.loc[earlier, "facility_id"] = unseen

    rebuilt = features.build_features(latest, perturbed, smoke_config)
    original = smoke_features.loc[
        smoke_features["sample_id"] == latest["sample_id"].iloc[0]
    ]

    with pytest.raises(AssertionError):
        pd.testing.assert_frame_equal(
            rebuilt.reset_index(drop=True), original.reset_index(drop=True)
        )


# --- the shuffled-label negative control ------------------------------


def _majority_prior(labels: pd.Series) -> float:
    """Return the share of the commonest class.

    Args:
        labels: Training labels.

    Returns:
        The accuracy a constant predictor of the commonest class scores.
    """
    return float(labels.value_counts(normalize=True).iloc[0])


def _bootstrap_standard_error(prior: float, rows: int) -> float:
    """Return the sampling error of an accuracy near ``prior``.

    Args:
        prior: The accuracy being bounded.
        rows: Rows the accuracy was measured on.

    Returns:
        One standard error.
    """
    return float(np.sqrt(max(prior * (1.0 - prior), 0.0) / max(rows, 1)))


def _shuffled(column: pd.Series, seed: int) -> pd.Series:
    """Return the labels in a seeded random order.

    Args:
        column: The target column.
        seed: Seed for the permutation.

    Returns:
        The same values, independently permuted.
    """
    generator = np.random.default_rng(seed)
    order = generator.permutation(len(column))
    return pd.Series(
        column.to_numpy()[order], index=column.index, name=column.name
    )


def _shuffled_control(
    head: str,
    training_rows: pd.DataFrame,
    holdout_rows: pd.DataFrame,
    smoke_samples: pd.DataFrame,
    smoke_config: config_module.Config,
    seed: int,
) -> tuple[float, float, float]:
    """Fit one head on shuffled labels and score it on unshuffled rows.

    Scoring on the rows that were fitted would measure memorisation, not
    leakage: a tree ensemble with capacity fits permuted labels in-sample
    whatever the features contain. The signal only means something on
    rows the fit never saw, whose labels were never shuffled.

    Args:
        head: One of the declared head names.
        training_rows: Feature rows to fit on.
        holdout_rows: Feature rows to score on, held out of the fit.
        smoke_samples: The sample table carrying the targets.
        smoke_config: Validated configuration.
        seed: Seed for the label permutation.

    Returns:
        The scored accuracy, the majority prior it is bounded by, and the
        tolerance allowed above that prior.
    """
    column = train.TARGET_COLUMNS[head]
    fit_targets = train.align_targets(training_rows, smoke_samples)
    shuffled = fit_targets.assign(
        **{column: _shuffled(fit_targets[column], seed=seed)}
    )
    design = train.build_design(head, training_rows, shuffled, smoke_config)
    fitted = train.fit_head(head, design, smoke_config)

    scored = train.build_design(
        head,
        holdout_rows,
        train.align_targets(holdout_rows, smoke_samples),
        smoke_config,
    )
    predicted = np.asarray(
        fitted.model.predict(scored.pool(labelled=False))
    ).ravel()

    accuracy = float(
        (
            pd.Series(predicted).astype(str).to_numpy()
            == scored.labels.astype(str).to_numpy()
        ).mean()
    )
    prior = _majority_prior(design.labels)
    tolerance = max(
        _NOISE_FLOOR,
        _NOISE_SIGMAS * _bootstrap_standard_error(prior, scored.samples()),
    )
    return accuracy, prior, tolerance


@pytest.mark.parametrize("head", list(train.HEAD_NAMES))
def test_a_head_trained_on_shuffled_labels_learns_nothing(
    training_rows, validation_rows, smoke_samples, smoke_config, head
):
    accuracy, prior, tolerance = _shuffled_control(
        head,
        training_rows,
        validation_rows,
        smoke_samples,
        smoke_config,
        seed=smoke_config.seed,
    )

    assert accuracy <= prior + tolerance, (
        f"head {head!r} scored {accuracy:.4f} on rows held out of a fit "
        f"whose labels were shuffled, against a majority prior of "
        f"{prior:.4f}; anything above {prior + tolerance:.4f} means it is "
        "reading the target through an undeclared channel"
    )


@pytest.mark.parametrize("head", list(train.HEAD_NAMES))
def test_the_shuffled_control_is_stable_across_permutations(
    training_rows, validation_rows, smoke_samples, smoke_config, head
):
    # One permutation could be lucky. A second, independently seeded one
    # must clear the same bound, or the control is a coin flip.
    accuracy, prior, tolerance = _shuffled_control(
        head,
        training_rows,
        validation_rows,
        smoke_samples,
        smoke_config,
        seed=smoke_config.seed + 977,
    )

    assert accuracy <= prior + tolerance


def test_the_control_fires_when_a_target_is_planted_in_the_features(
    training_rows, validation_rows, smoke_samples, smoke_config
):
    # A negative control that cannot fail proves nothing. Plant the
    # answer directly in the feature matrix — the exact leak the control
    # exists to find — and it must fire. This is deliberately not a
    # claim about how well the real head predicts: it is a claim that
    # the instrument has a needle.
    column = train.TARGET_COLUMNS[train.FACILITY]
    fit_targets = train.align_targets(training_rows, smoke_samples)
    scored_targets = train.align_targets(validation_rows, smoke_samples)
    shuffled = fit_targets.assign(
        **{column: _shuffled(fit_targets[column], seed=smoke_config.seed)}
    )

    design = train.build_design(
        train.FACILITY, training_rows, shuffled, smoke_config
    )
    scored = train.build_design(
        train.FACILITY, validation_rows, scored_targets, smoke_config
    )
    # The leak: each row is handed the label its fit was given, and each
    # scored row is handed its own true label.
    leaked_fit = design.matrix.assign(
        planted=shuffled[column].astype(str).to_numpy()
    )
    leaked_scored = scored.matrix.assign(
        planted=scored_targets[column].astype(str).to_numpy()
    )
    categoricals = (*design.categoricals, "planted")
    fitted = train.fit_head(
        train.FACILITY,
        train.Design(
            matrix=leaked_fit,
            labels=design.labels,
            categoricals=categoricals,
        ),
        smoke_config,
    )

    predicted = np.asarray(
        fitted.model.predict(
            train.Design(
                matrix=leaked_scored,
                labels=scored.labels,
                categoricals=categoricals,
            ).pool(labelled=False)
        )
    ).ravel()

    # The planted column reproduces the SHUFFLED label the fit saw, so a
    # head that reads it scores far above the prior on rows it never saw.
    agreement = float(
        (
            pd.Series(predicted).astype(str).to_numpy()
            == scored_targets[column].astype(str).to_numpy()
        ).mean()
    )
    prior = _majority_prior(design.labels)

    assert agreement > prior + _NOISE_FLOOR


def test_shuffling_preserves_the_label_distribution(
    training_rows, smoke_samples, smoke_config
):
    # If shuffling changed the class balance, the majority prior the
    # bound is built from would describe a different problem.
    targets = train.align_targets(training_rows, smoke_samples)
    column = train.TARGET_COLUMNS[train.FACILITY]

    shuffled = _shuffled(targets[column], seed=smoke_config.seed)

    assert (
        shuffled.value_counts()
        .sort_index()
        .equals(targets[column].value_counts().sort_index())
    )


def test_shuffling_is_seeded_and_repeatable(
    training_rows, smoke_samples, smoke_config
):
    targets = train.align_targets(training_rows, smoke_samples)
    column = train.TARGET_COLUMNS[train.FACILITY]

    first = _shuffled(targets[column], seed=smoke_config.seed)
    second = _shuffled(targets[column], seed=smoke_config.seed)

    pd.testing.assert_series_equal(first, second)
