"""baseline schema

Revision ID: 810ae8d17b79
Revises:
Create Date: 2026-08-15 15:42:12.722601

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "810ae8d17b79"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("booking_id", sa.Text(), nullable=False),
        sa.Column("resident_id", sa.Text(), nullable=False),
        sa.Column("facility_id", sa.Text(), nullable=False),
        sa.Column(
            "booking_timestamp", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "usage_timestamp", sa.DateTime(timezone=True), nullable=False
        ),
        sa.CheckConstraint(
            "booking_timestamp < usage_timestamp",
            name="ck_bookings_booked_before_used",
        ),
        sa.PrimaryKeyConstraint("booking_id"),
    )
    op.create_index(
        op.f("ix_bookings_booking_timestamp"),
        "bookings",
        ["booking_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bookings_resident_id"),
        "bookings",
        ["resident_id"],
        unique=False,
    )
    op.create_table(
        "predictions",
        sa.Column("track", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("sample_id", sa.Text(), nullable=False),
        sa.Column("predicted_facility_id", sa.Text(), nullable=True),
        sa.Column("predicted_usage_weekday", sa.Integer(), nullable=True),
        sa.Column("predicted_usage_hour", sa.Integer(), nullable=True),
        sa.Column("predicted_delay_minutes", sa.Float(), nullable=True),
        sa.Column("predicted_transition_facility_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("track", "model", "sample_id"),
    )
    op.create_table(
        "samples",
        sa.Column("sample_id", sa.Text(), nullable=False),
        sa.Column("resident_id", sa.Text(), nullable=False),
        sa.Column("origin", sa.DateTime(timezone=True), nullable=False),
        sa.Column("origin_booking_id", sa.Text(), nullable=False),
        sa.Column("n_prior_bookings", sa.Integer(), nullable=False),
        sa.Column("target_booking_id", sa.Text(), nullable=False),
        sa.Column(
            "target_booking_timestamp",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "target_usage_timestamp", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("target_facility_id", sa.Text(), nullable=False),
        sa.Column("target_usage_weekday", sa.Integer(), nullable=False),
        sa.Column("target_usage_hour", sa.Integer(), nullable=False),
        sa.Column("notification_delay_minutes", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "origin < target_booking_timestamp",
            name="ck_samples_origin_precedes_target",
        ),
        sa.PrimaryKeyConstraint("sample_id"),
    )
    op.create_index(
        op.f("ix_samples_resident_id"), "samples", ["resident_id"], unique=False
    )
    op.create_index(
        op.f("ix_samples_target_booking_timestamp"),
        "samples",
        ["target_booking_timestamp"],
        unique=False,
    )
    op.create_table(
        "splits",
        sa.Column("sample_id", sa.Text(), nullable=False),
        sa.Column("split", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("sample_id"),
    )
    op.create_index(op.f("ix_splits_split"), "splits", ["split"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_splits_split"), table_name="splits")
    op.drop_table("splits")
    op.drop_index(
        op.f("ix_samples_target_booking_timestamp"), table_name="samples"
    )
    op.drop_index(op.f("ix_samples_resident_id"), table_name="samples")
    op.drop_table("samples")
    op.drop_table("predictions")
    op.drop_index(op.f("ix_bookings_resident_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_booking_timestamp"), table_name="bookings")
    op.drop_table("bookings")
    # ### end Alembic commands ###
